version: '3.4'

services:
  tobybot:
    restart: unless-stopped
    image: tobybot
    container_name: TobyBot
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 6845:6845
    volumes:
      - data:/data
volumes:
  data:
networks:
  default:
    external: 
      name: phpmyadmin