version: '3.4'

services:
  tobybot-database:
    restart: unless-stopped
    image: mariadb:latest
    container_name: MariaDB-TobyBot
    command: mariadbd --log-bin
    networks:
      - tobybot
      - db_manage
    env_file:
        - .env
    volumes:
      - mysql:/var/lib/mysql
  tobybot:
    restart: "no"
    image: tobybot:4.0.0
    container_name: TobyBot
    tty: true
    stdin_open: true
    command: wait-for MariaDB-TobyBot:3306 -- dumb-init node ./src/index.js
    networks:
      - tobybot
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - "tobybot-database"
    env_file:
        - .env
    volumes:
      - data:/data
volumes:
  data:
  mysql:
networks:
  tobybot:
    driver: bridge
    internal: true
  db_manage:
    external: true