version: '3.4'

services:
  tobybot:
    restart: unless-stopped
    image: tobybot:4.0.0
    container_name: TobyBot
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - "tobybot-database"
    env_file:
        - .env
    volumes:
      - data:/data
  tobybot-database:
    restart: unless-stopped
    image: mariadb:latest
    container_name: MariaDB-TobyBot
    command: mariadbd --log-bin
    env_file:
        - .env
volumes:
  data:
networks:
  tobybot:
    driver: bridge
    internal: true