version: '3.4'

services:
  tobybot:
    restart: unless-stopped
    image: tobybot:4.0.0
    container_name: TobyBot
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - "tobybot-database"
    env_file:
        - .env
    volumes:
      - data:/data
    ports:
    - 6845:6845
  tobybot-database:
    restart: unless-stopped
    image: mariadb:latest
    container_name: MariaDB-TobyBot
    command: mariadbd --log-bin
    env_file:
        - .env
  tobybot-website:
    image: tobybot-gui:8.1-apache
    container_name: TobyBot-GUI
    env_file:
        - .env
    ports:
    - 8888:80
volumes:
  data:
networks:
  tobybot:
    driver: bridge
    internal: true