version: '3.4'

services:
  tobybot-database:
    restart: unless-stopped
    image: mariadb:latest
    container_name: MariaDB-TobyBot
    command: mariadbd --log-bin
    networks:
      - tobybot
    environment:
      - MARIADB_CHARSET=UTF8MB4_UNICODE_CI
    env_file:
        - .env
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$$MARIADB_ROOT_PASSWORD --execute \"SELECT 'Database up and running !' as '';\""
      interval: 3s
      timeout: 1s
      retries: 5
  tobybot:
    restart: "no"
    image: tobybot:alpha4.0.0
    container_name: TobyBot
    tty: true
    stdin_open: true
    command: npm run start
    networks:
      - tobybot
      - bridge
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      tobybot-database:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - MARIADB_CHARSET=UTF8MB4_UNICODE_CI
    env_file:
        - .env
    volumes:
      - data:/data
volumes:
  data:
  mysql:
networks:
  tobybot:
    driver: bridge
    internal: true
  bridge:
    driver: bridge
  nginx_proxy_manager:
   external: true