version: '2.1'
services:
  app:
    image: 'ghcr.io/parkervcp/yolks:nodejs_17'
    restart: unless-stopped
    container_name: TobyBot
    networks:
      - tobybot
      - bridge
    ports:
      - 20000:20000
    env_file:
      - tobybot.env
    volumes:
      - tobybot-v3_volume:/home/container
  db:
    container_name: TobyBot-MariaDB
    image: mariadb
    restart: unless-stopped
    networks:
      - tobybot
    environment:
      - MARIADB_ROOT_PASSWORD=xvNUiUhjmmftPMiyWagAcR6sEtQxPt
    volumes:
      - tobybot-v3_db-volume:/home/container
networks:
  tobybot:
    external: true
  bridge:
    name: custombridge
    external: true
volumes:
  tobybot-v3_volume:
  tobybot-v3_db-volume: